"""Changed datetime datatype

Revision ID: d781a1700f8b
Revises: 2a77e70c1ea1
Create Date: 2022-11-23 13:25:14.877968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import DATETIME



# revision identifiers, used by Alembic.
revision = 'd781a1700f8b'
down_revision = '2a77e70c1ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    op.alter_column('event_analysis_details', 'start_time', existing_type=sa.DateTime, type_=DATETIME(fsp=6))
    op.alter_column('event_analysis_details', 'end_time', existing_type=sa.DateTime, type_=DATETIME(fsp=6))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    op.alter_column('event_analysis_details', 'start_time', type_=sa.DateTime, existing_type=DATETIME(fsp=6))
    op.alter_column('event_analysis_details', 'end_time', type_=sa.DateTime, existing_type=DATETIME(fsp=6))
    # ### end Alembic commands ###
